### PR TITLE
Initial commit of 18F's Ruby Ecosystem Guide

### PR DESCRIPTION
**Pull request by ccostino**
This changeset adds the initial content of our Ruby Ecosystem Guide originally written in Google Docs.

### CODE REVIEW

**Comment by ccostino** [comment]
cc @jeremiak and @mbland

**Comment by ccostino** [comment]
@brittag:  I've incorporated all of your copy edits and tried to improve the Gemset section a bit more.  If you wouldn't mind taking another look I would appreciate it!

**Comment by brittag** [comment]
@ccostino I edited a couple more little things. I'm also curious about this sentence: "With Bundler installed you are able to utilize a project's `Gemfile` (or define your own for your project)." This could imply that you need Bundler in order to use a Gemfile - is that what you mean?

**Comment by mbland** [comment]
@brittag You do need Bundler, yes. Maybe a link to bundler.io would be apropos.

**Pull request merged**
